#pragma once

enum CollisionShape 
{
	COLLISION_SHAPE_SPHERE,
	COLLISION_SHAPE_BOX,
	COLLISION_SHAPE_NUM
};

enum CollisionCategory 
{
	COLLISION_CATEGORY_PLAYER,
	COLLISION_CATEGORY_BULLET,
	COLLISION_CATEGORY_ENEMY,
	COLLISION_CATEGORY_BOX,
	COLLISION_CATEGORY_OBSTACLES,
	COLLISION_CATEGORY_NUM,
};

enum CollisionState {
	COLLISION_STATE_ACTIVE,
	COLLISION_STATE_UNUSE,
	COLLISION_STATE_NONE,
};
