#pragma once

constexpr int LOAD_SOUND_MAX = 50;
 
enum SOUNDGROUP
{
	SOUND_GROUP_TITLE,
	SOUND_GROUP_PLAY,
	SOUND_GROUP_CLEAR,
	SOUND_GROUP_GAMEOVER,
	SOUND_GROUP_MAX
};

enum Sound_ID
{
	SOUND_ID_BGM_TITLE_SCENE,
	SOUND_ID_BGM_PLAY_SCENE,
	SOUND_ID_BGM_CLEAR_SCENE,
	SOUND_ID_BGM_GAMEOVER_SCENE,
	SOUND_ID_SE_CLICK_ENTER,
	SOUND_ID_SE_RESTART,
	SOUND_ID_SE_PLAYER_JUMP,
	SOUND_ID_SE_PLAYER_BULLET_SHOT,
	SOUND_ID_SE_HIT_BOX,
	SOUND_ID_SE_START_ATTRACT,
	SOUND_ID_SE_OBJECT_TRAMPOLINE,
	SOUND_ID_MAX,
};

struct SoundParameter
{
	int id;
	char file_path[128];
};

const SoundParameter SOUND_DATABASE[LOAD_SOUND_MAX] =
{
	{SOUND_ID_BGM_TITLE_SCENE,"Data/Sound/BGM/Title_Scene.mp3"},
	{SOUND_ID_BGM_PLAY_SCENE,"Data/Sound/BGM/Play_Scene.mp3"},
	{SOUND_ID_BGM_CLEAR_SCENE,"Data/Sound/BGM/Clear_Scene.mp3"},
	{SOUND_ID_BGM_GAMEOVER_SCENE,"Data/Sound/BGM/GameOver_Scene.mp3"},
	{SOUND_ID_SE_CLICK_ENTER,"Data/Sound/Click/Click_Enter.wav"},
	{SOUND_ID_SE_RESTART,"Data/Sound/Click/Restart.wav"},
	{SOUND_ID_SE_PLAYER_JUMP,"Data/Sound/Player/Jump.wav"},
	{SOUND_ID_SE_PLAYER_BULLET_SHOT,"Data/Sound/Fire/Fire.wav"},
	{SOUND_ID_SE_HIT_BOX,"Data/Sound/Hit/Hit_Box.wav"},
	{SOUND_ID_SE_START_ATTRACT,"Data/Sound/Box/Attract.wav"},
	{SOUND_ID_SE_OBJECT_TRAMPOLINE,"Data/Sound/Object/Trampoline.wav"}
};

const int SOUND_GROUP[SOUND_GROUP_MAX][LOAD_SOUND_MAX] =
{
	{// SOUND_GROUP_TITLE
		SOUND_ID_BGM_TITLE_SCENE,
		SOUND_ID_SE_CLICK_ENTER,
		-1,
	},

	{//SOUND_GROUP_PLAY
		SOUND_ID_BGM_PLAY_SCENE,
		SOUND_ID_SE_RESTART,
		SOUND_ID_SE_PLAYER_JUMP,
		SOUND_ID_SE_PLAYER_BULLET_SHOT,
		SOUND_ID_SE_HIT_BOX,
		SOUND_ID_SE_START_ATTRACT,
		SOUND_ID_SE_OBJECT_TRAMPOLINE,
		-1,
	},

	{//SOUND_GROUP_CLEAR
		SOUND_ID_BGM_CLEAR_SCENE,
		SOUND_ID_SE_CLICK_ENTER,
		-1,
	},

	{//SOUND_GROUP_GAMEOVER
		SOUND_ID_BGM_GAMEOVER_SCENE,
		SOUND_ID_SE_CLICK_ENTER,
		-1,
	}
};